name: Auto approve
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'justin-elias'
        with:
          github-token: "${{ secrets.ACTION_TOKEN }}"
