name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    types: [closed]
    branches: 
      - master
jobs:
  build-bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          git-message: 'chore(release): {version}'
