name: Pull Request on Branch Push
on:
  push:
    branches:
      - bump-version
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        if: github.actor == 'justin-elias'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
