name: ESLint
on:
  push:
    branches-ignore:
      - master
      - staging
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
          FROM_BRANCH: ${GITHUB_REF##*/}
          TO_BRANCH: "staging"
