name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: --fix pages/**/*.js pages-sections/**/*.js components/**/*.js Scripts/**/*.js tests/**/*.js assets/theme.js
